### ISSUE TITLE
not working. // ใช้งานไม่ได้

### ISSUE THREAD

**Issue by DearTanakorn** [rayriffy/truewallet#8]
it show // มันขึ้นแจ้งมาว่า mag-400 ไม่รู้ว่าตัวนี้ได้แก้ api ของ wallet หรือยังที่ต้องใช้ค่าอะไรต่างๆ
{
  code: 'MAG-400',
  data: null,
  title: 'ไม่สามารถทำรายการได้',
  message: 'ข้อมูลไม่เพียงพอ\nกรุณาแก้ไขข้อมูลแล้วทำรายการใหม่อีกครั้ง'
}

**Comment by freealife** [comment]
{
  code: '501',
  namespace: 'TMN-MAG',
  titleTh: 'กรุณาอัปเดตแอปพลิเคชัน',
  titleEn: 'Update required',
  messageTh: 'เพื่อความปลอดภัยและการใช้งานที่สมบูรณ์\n' +
    'กรุณาอัปเดตแอปพลิเคชันเวอร์ชันล่าสุด',
  messageEn: 'For best experience,\nplease update your application to the latest version.',
  originalMessage: 'Update required',
  developerMessage: null,
  data: {}
}

ตอนนี้ผมลอง Check Balance ลองดูละ ติดเหมือนต้อง Update Version Application

**Comment by rayriffy** [comment]
API V1 is deprecated, there will be no any update will be made to this repository anymore.
